# -*- coding: utf-8 -*-
"""Copy of Netflix vs Tv shows analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmKI0EZNepdvgS7ya3QOjk3bRHdb3KZz
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("netflix_titles.csv")
df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

df["director"].fillna("Unknown",inplace=True)
df["cast"].fillna("Not Available",inplace=True)
df["country"].fillna("Unknown",inplace=True)
df.dropna(inplace=True)

df.isnull().sum()

df["type"].value_counts().plot(kind="bar")
plt.title("Movie vs TV Shows")
plt.xlabel("type")
plt.ylabel("count")
plt.show()

"""Usually Netflix has more movies than tv shows.

"""

year=df["release_year"].value_counts().sort_index()

plt.plot(year.index, year.values)
plt.title("Content Released Over Years")
plt.xlabel("year")
plt.ylabel("count")
plt.show()

"""Streaming platforms became popular after 2015."""

df["country"].value_counts().head(5).plot(kind="bar")
plt.title("Top 5 Countries")
plt.xlabel("country")
plt.ylabel("count")
plt.show()

"""USA usually produces most content,other countries like Japan and the United Kingdom contribute significantly less."""

df["rating"].value_counts().head(5).plot(kind="pie",
autopct="%1.1f%%")
plt.title("Rating Distribution")
plt.ylabel("")
plt.show()

"""Netflix has more shows for adults and teens than for kids."""

df["type"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.title("Content Type Percentage")
plt.ylabel("")
plt.show()

"""Movies are more because they are faster to produce than TV shows.

This project shows that Netflix focuses more on movies than TV shows and has rapidly expanded its content library in recent years. Most content comes from a few major countries, especially the United States, and the majority of titles are aimed at mature audiences. Data visualization helps easily understand trends and patterns in streaming platforms.
"""